/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace MyContract {
  export type PradeepStruct = {
    id: PromiseOrValue<BigNumberish>;
    age: PromiseOrValue<BigNumberish>;
  };

  export type PradeepStructOutput = [BigNumber, BigNumber] & {
    id: BigNumber;
    age: BigNumber;
  };
}

export interface MyContractInterface extends utils.Interface {
  functions: {
    "data()": FunctionFragment;
    "owner()": FunctionFragment;
    "role()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "data" | "owner" | "role"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "data", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "role", values?: undefined): string;

  decodeFunctionResult(functionFragment: "data", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "role", data: BytesLike): Result;

  events: {};
}

export interface MyContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MyContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    data(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { id: BigNumber; age: BigNumber }>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    role(overrides?: CallOverrides): Promise<[string]>;
  };

  data(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { id: BigNumber; age: BigNumber }>;

  owner(overrides?: CallOverrides): Promise<string>;

  role(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    data(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { id: BigNumber; age: BigNumber }>;

    owner(overrides?: CallOverrides): Promise<string>;

    role(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    data(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    role(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    data(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    role(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
